# Configuración básica del sitio
title: "Huila Viajera - Experiencias Únicas en el Huila, Colombia"
description: "Descubre el Huila auténtico con Walter Tours. Desierto de La Tatacoa, San Agustín, experiencias gastronómicas y aventura extrema. Tours especializados desde 2024."
baseurl: ""
url: "https://colombiatravels.co"

# SEO y metadatos
author: "Walter Tours"
lang: "es-CO"
timezone: "America/Bogota"

# Configuración Jekyll básica
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 12
paginate_path: "/blog/page:num/"

# Sin plugins - solo Jekyll básico
plugins: []

# Collections para contenido estructurado
collections:
  destinos:
    output: true
    permalink: /:collection/:name/
  experiencias:
    output: true
    permalink: /:collection/:name/
  paquetes:
    output: true
    permalink: /:collection/:name/

# Configuración de layouts por defecto
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Walter Tours"
  - scope:
      path: ""
      type: "destinos"
    values:
      layout: "destino"
      schema_type: "TouristDestination"
  - scope:
      path: ""
      type: "experiencias"
    values:
      layout: "experiencia" 
      schema_type: "TouristAttraction"
  - scope:
      path: ""
      type: "paquetes"
    values:
      layout: "paquete"
      schema_type: "TouristTrip"

# Optimizaciones técnicas
sass:
  style: compressed
  sourcemap: never

# Archivos a excluir
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules
  - package.json
  - .git
  - .gitignore

# Variables del sitio
company:
  name: "Walter Tours"
  nit: "7721644-2"
  phone: "+57 XXX XXX XXXX"
  email: "info@waltertours.com"
  address: "Huila, Colombia"
  logo: "/assets/images/logo-walter-tours.webp"
  
# Schema.org datos base
schema:
  type: "TravelAgency"
  area_served: "Huila, Colombia"
  founding_date: "2024"
  
# GTM y tracking
gtm_id: "GTM-XXXXXXX"

# Configuración de imágenes
images_path: "/assets/images/"
default_image: "/assets/images/og-huila-default.webp"